all:
	g++ -o bin/fib fib.cpp
	g++ -o bin/sample sample.cpp
	g++ -o bin/best3 best3.cpp
	g++ -o bin/best3v2 best3v2.cpp
	g++ -o bin/histogram histogram.cpp
	cp english.txt bin/
	g++ -o bin/exercise2 exercise2.cpp
	g++ -o bin/best3 best3.cpp

clean:
	rm bin/fib
	rm bin/sample
	rm bin/best3
	rm bin/best3v2
	rm bin/histogram
	rm bin/exercise2
	

